version: "3.3"

services:
  app:
    container_name: url-shortener-api
    build: .
    image: url-shortener-api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8080:8080"
    links:
      - redis
    restart: always

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
